package xyy.fin.model;

import java.util.Date;

public class FinChgHistModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_chg_hist.id
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_chg_hist.from_id
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    private Integer fromId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_chg_hist.to_id
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    private Integer toId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_chg_hist.chg_ammount
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    private Long chgAmmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_chg_hist.chg_comment
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    private String chgComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_chg_hist.chg_time
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    private Date chgTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_chg_hist.id
     *
     * @return the value of fin_chg_hist.id
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_chg_hist.id
     *
     * @param id the value for fin_chg_hist.id
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_chg_hist.from_id
     *
     * @return the value of fin_chg_hist.from_id
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    public Integer getFromId() {
        return fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_chg_hist.from_id
     *
     * @param fromId the value for fin_chg_hist.from_id
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    public void setFromId(Integer fromId) {
        this.fromId = fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_chg_hist.to_id
     *
     * @return the value of fin_chg_hist.to_id
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    public Integer getToId() {
        return toId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_chg_hist.to_id
     *
     * @param toId the value for fin_chg_hist.to_id
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    public void setToId(Integer toId) {
        this.toId = toId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_chg_hist.chg_ammount
     *
     * @return the value of fin_chg_hist.chg_ammount
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    public Long getChgAmmount() {
        return chgAmmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_chg_hist.chg_ammount
     *
     * @param chgAmmount the value for fin_chg_hist.chg_ammount
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    public void setChgAmmount(Long chgAmmount) {
        this.chgAmmount = chgAmmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_chg_hist.chg_comment
     *
     * @return the value of fin_chg_hist.chg_comment
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    public String getChgComment() {
        return chgComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_chg_hist.chg_comment
     *
     * @param chgComment the value for fin_chg_hist.chg_comment
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    public void setChgComment(String chgComment) {
        this.chgComment = chgComment == null ? null : chgComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_chg_hist.chg_time
     *
     * @return the value of fin_chg_hist.chg_time
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    public Date getChgTime() {
        return chgTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_chg_hist.chg_time
     *
     * @param chgTime the value for fin_chg_hist.chg_time
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    public void setChgTime(Date chgTime) {
        this.chgTime = chgTime;
    }
}