package xyy.fin.model;

public class FinItemModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_items.id
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_items.item_name
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    private String itemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_items.item_balance
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    private Long itemBalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_items.item_type
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    private String itemType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_items.id
     *
     * @return the value of fin_items.id
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_items.id
     *
     * @param id the value for fin_items.id
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_items.item_name
     *
     * @return the value of fin_items.item_name
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_items.item_name
     *
     * @param itemName the value for fin_items.item_name
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_items.item_balance
     *
     * @return the value of fin_items.item_balance
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    public Long getItemBalance() {
        return itemBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_items.item_balance
     *
     * @param itemBalance the value for fin_items.item_balance
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    public void setItemBalance(Long itemBalance) {
        this.itemBalance = itemBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_items.item_type
     *
     * @return the value of fin_items.item_type
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    public String getItemType() {
        return itemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_items.item_type
     *
     * @param itemType the value for fin_items.item_type
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    public void setItemType(String itemType) {
        this.itemType = itemType == null ? null : itemType.trim();
    }
}