server:
  port: 8002
  context-path: /finance-api
security.basic.enabled: false

spring: 
    mail:  
        host: smtp.qq.com
        username: 390380730@qq.com
        password: vlrsylanqsvnbghj
        properties:
          mail:
            smtp:
              auth: true
              starttls: 
                enable: true
                required: true
      
    datasource:
      url: jdbc:mysql://localhost:3306/xyy_fin?useSSL=false&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 123456
      driverClassName: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: config,stat,wall,log4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

logging:
  file: logs/finace-api.log #can use relative position for the log configuration
  level:
    root: info
    org.apache.ibatis: debug
    java.sql.Connection: debug
    java.sql.Statement: debug
    java.sql.PreparedStatement: debug
    com.alibaba.druid.sql: debug
    com.alibaba.druid.proxy.jdbc: info
    org.apache.ibatis.transaction.managed: info
    druid.sql: info
    com.nowbook.mm.platform: debug
    org.springframework.security: debug
    
    
  