package xyy.fin.model;

import java.util.Date;

public class FinMonthlySnapModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_monthly_snapshot.id
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_monthly_snapshot.snap_item
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    private String snapItem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_monthly_snapshot.snap_time
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    private Date snapTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_monthly_snapshot.snap_balance
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    private Long snapBalance;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_monthly_snapshot.id
     *
     * @return the value of fin_monthly_snapshot.id
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_monthly_snapshot.id
     *
     * @param id the value for fin_monthly_snapshot.id
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_monthly_snapshot.snap_item
     *
     * @return the value of fin_monthly_snapshot.snap_item
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    public String getSnapItem() {
        return snapItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_monthly_snapshot.snap_item
     *
     * @param snapItem the value for fin_monthly_snapshot.snap_item
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    public void setSnapItem(String snapItem) {
        this.snapItem = snapItem == null ? null : snapItem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_monthly_snapshot.snap_time
     *
     * @return the value of fin_monthly_snapshot.snap_time
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    public Date getSnapTime() {
        return snapTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_monthly_snapshot.snap_time
     *
     * @param snapTime the value for fin_monthly_snapshot.snap_time
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    public void setSnapTime(Date snapTime) {
        this.snapTime = snapTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_monthly_snapshot.snap_balance
     *
     * @return the value of fin_monthly_snapshot.snap_balance
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    public Long getSnapBalance() {
        return snapBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_monthly_snapshot.snap_balance
     *
     * @param snapBalance the value for fin_monthly_snapshot.snap_balance
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    public void setSnapBalance(Long snapBalance) {
        this.snapBalance = snapBalance;
    }
}