package xyy.fin.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import xyy.fin.model.FinMonthlySnapModel;
import xyy.fin.model.FinMonthlySnapModelExample;

public interface FinMonthlySnapModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fin_monthly_snapshot
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    long countByExample(FinMonthlySnapModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fin_monthly_snapshot
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    int deleteByExample(FinMonthlySnapModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fin_monthly_snapshot
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fin_monthly_snapshot
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    int insert(FinMonthlySnapModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fin_monthly_snapshot
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    int insertSelective(FinMonthlySnapModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fin_monthly_snapshot
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    List<FinMonthlySnapModel> selectByExample(FinMonthlySnapModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fin_monthly_snapshot
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    FinMonthlySnapModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fin_monthly_snapshot
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    int updateByExampleSelective(@Param("record") FinMonthlySnapModel record, @Param("example") FinMonthlySnapModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fin_monthly_snapshot
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    int updateByExample(@Param("record") FinMonthlySnapModel record, @Param("example") FinMonthlySnapModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fin_monthly_snapshot
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    int updateByPrimaryKeySelective(FinMonthlySnapModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fin_monthly_snapshot
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    int updateByPrimaryKey(FinMonthlySnapModel record);
}