package xyy.fin.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import xyy.fin.model.FinChgHistModel;
import xyy.fin.model.FinChgHistModelExample;

public interface FinChgHistModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fin_chg_hist
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    long countByExample(FinChgHistModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fin_chg_hist
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    int deleteByExample(FinChgHistModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fin_chg_hist
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fin_chg_hist
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    int insert(FinChgHistModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fin_chg_hist
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    int insertSelective(FinChgHistModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fin_chg_hist
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    List<FinChgHistModel> selectByExample(FinChgHistModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fin_chg_hist
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    FinChgHistModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fin_chg_hist
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    int updateByExampleSelective(@Param("record") FinChgHistModel record, @Param("example") FinChgHistModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fin_chg_hist
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    int updateByExample(@Param("record") FinChgHistModel record, @Param("example") FinChgHistModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fin_chg_hist
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    int updateByPrimaryKeySelective(FinChgHistModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fin_chg_hist
     *
     * @mbg.generated Thu Dec 28 15:57:25 CST 2017
     */
    int updateByPrimaryKey(FinChgHistModel record);
}